"""Criação das tabelas

Revision ID: 433260ff520d
Revises: 9b36c15da4da
Create Date: 2025-07-17 08:04:41.788779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433260ff520d'
down_revision: Union[str, None] = '9b36c15da4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificacao', sa.String(length=14), nullable=False),
    sa.Column('nome', sa.String(length=254), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='statusenum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificacao'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('frascos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificacao', sa.String(length=254), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='statusenum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificacao')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('permissao', sa.Enum('ADMINISTRADOR', 'OPERADOR_ADMINISTRADOR', 'OPERADOR_ESTOQUE', name='permissaoenum'), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='statusenum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('estoque_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_frasco', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_frasco'], ['frascos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_frasco', sa.Integer(), nullable=False),
    sa.Column('estoque_real', sa.Integer(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_frasco'], ['frascos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('responsavel', sa.String(length=254), nullable=True),
    sa.Column('assinatura', sa.LargeBinary(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('EXTERNO', 'INTERNO', name='tipomovimentacaoenum'), nullable=False),
    sa.Column('detalhe_movimentacao', sa.Enum('EMPRESTIMO', 'DEVOLUCAO', 'SOLICITACAO', 'AJUSTE', 'CANCELAMENTO', 'COMPRA', 'REPOSICAO', name='detalhemovimentacaoenum'), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'CONCLUIDO', 'CANCELADO', name='statusenum'), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_frasco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('id_frasco', sa.Integer(), nullable=False),
    sa.Column('id_movimentacao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_frasco'], ['frascos.id'], ),
    sa.ForeignKeyConstraint(['id_movimentacao'], ['movimentacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lembretes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('id_estoque_empresa', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CONCLUIDO', name='statusenum'), nullable=False),
    sa.ForeignKeyConstraint(['id_estoque_empresa'], ['estoque_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_item_frasco', sa.Integer(), nullable=False),
    sa.Column('estoque_antes_empresa', sa.Integer(), nullable=False),
    sa.Column('estoque_depois_empresa', sa.Integer(), nullable=False),
    sa.Column('estoque_antes_cliente', sa.Integer(), nullable=True),
    sa.Column('estoque_depois_cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_item_frasco'], ['item_frasco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_estoque')
    op.drop_table('lembretes')
    op.drop_table('item_frasco')
    op.drop_table('movimentacoes')
    op.drop_table('estoque_empresa')
    op.drop_table('estoque_cliente')
    op.drop_table('usuarios')
    op.drop_table('frascos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
