"""incluido a coluna comercial no Model Cliente

Revision ID: 8bc1676b4a36
Revises: 433260ff520d
Create Date: 2025-07-17 08:17:59.094766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc1676b4a36'
down_revision: Union[str, None] = '433260ff520d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('comercial', sa.Enum('COMERCIAL_1', 'COMERCIAL_2', 'COMERCIAL_4', 'COMERCIAL_7', name='comercialenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'comercial')
    # ### end Alembic commands ###
