"""Criação das tabelas iniciais

Revision ID: 9b36c15da4da
Revises: 
Create Date: 2025-07-17 07:57:21.816832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b36c15da4da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frascos')
    op.drop_table('lembretes')
    op.drop_table('clientes')
    op.drop_table('estoque_cliente')
    op.drop_table('estoque_empresa')
    op.drop_table('item_frasco')
    op.drop_table('movimentacoes')
    op.drop_table('usuarios')
    op.drop_table('historico_estoque')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_estoque',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_item_frasco', sa.INTEGER(), nullable=False),
    sa.Column('estoque_antes_empresa', sa.INTEGER(), nullable=False),
    sa.Column('estoque_depois_empresa', sa.INTEGER(), nullable=False),
    sa.Column('estoque_antes_cliente', sa.INTEGER(), nullable=True),
    sa.Column('estoque_depois_cliente', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_item_frasco'], ['item_frasco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('login', sa.VARCHAR(length=100), nullable=False),
    sa.Column('senha', sa.VARCHAR(length=255), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), nullable=False),
    sa.Column('permissao', sa.VARCHAR(length=22), nullable=True),
    sa.Column('status', sa.VARCHAR(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('movimentacoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.DATETIME(), nullable=True),
    sa.Column('responsavel', sa.VARCHAR(length=254), nullable=True),
    sa.Column('assinatura', sa.BLOB(), nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=7), nullable=False),
    sa.Column('detalhe_movimentacao', sa.VARCHAR(length=12), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_frasco',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('id_frasco', sa.INTEGER(), nullable=False),
    sa.Column('id_movimentacao', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_frasco'], ['frascos.id'], ),
    sa.ForeignKeyConstraint(['id_movimentacao'], ['movimentacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque_empresa',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_frasco', sa.INTEGER(), nullable=False),
    sa.Column('estoque_real', sa.INTEGER(), nullable=False),
    sa.Column('estoque_minimo', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_frasco'], ['frascos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque_cliente',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), nullable=False),
    sa.Column('id_frasco', sa.INTEGER(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_frasco'], ['frascos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('identificacao', sa.VARCHAR(length=14), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=254), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=11), nullable=True),
    sa.Column('email', sa.VARCHAR(length=254), nullable=True),
    sa.Column('status', sa.VARCHAR(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificacao'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('lembretes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.DATETIME(), nullable=True),
    sa.Column('id_estoque_empresa', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.ForeignKeyConstraint(['id_estoque_empresa'], ['estoque_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frascos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('identificacao', sa.VARCHAR(length=254), nullable=False),
    sa.Column('capacidade', sa.INTEGER(), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificacao')
    )
    # ### end Alembic commands ###
